---
title: "week-of-lols"
description: |
  Things I learned while keeping track of everything I laughed at for a week.
author:
  - name: Caro Buck
    url: https://example.com/norajones
date: 2022-01-10
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

One week, I decided to track every time I laughed. Turns out, perhaps unsurprisingly, if you know me in real life, I laugh a lot so this was a bit harder than I thought it would be.

Things I learned: 
* Appreciate the small things- if I hadn't written this stuff down, I probably wouldn't have remembered my roommate talking about vacuuming the ceiling as her excuse to get out of Zoom meetings. Life is about the little stuff just as much as the big. 
* I tend to laugh to ease conversation (I found this was the case with coworkers a lot)
* I have different "flavors" of laughter, depending on the context/situation. My favorite kind is where I simply Can. Not. Stop. Laughing. In fact, I go silent I'm laughing so hard.
* Some of the stuff that makes me laugh is really not that funny. 


# TODO: pull stuff up from viz/data literacy deck! 

Cheers!



